name: youtube-shorts-5-slots

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Forcer un post immédiat pour ce run"
        type: boolean
        default: false
  schedule:
    - cron: "2-59/5 * * * *"

permissions:
  contents: write

concurrency:
  group: youtube-post
  cancel-in-progress: false

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Random jitter (0-30s)
        run: sleep $((RANDOM % 30))

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "google-api-python-client" "oauth2client" "progressbar2"
          pip install "git+https://github.com/tokland/youtube-upload.git"

      - name: Write YouTube OAuth files (from secrets)
        run: |
          echo "${{ secrets.YT_CLIENT_SECRETS_JSON_B64 }}" | base64 -d > client_secrets.json
          echo "${{ secrets.YT_CREDENTIALS_JSON_B64 }}" | base64 -d > youtube_credentials.json

      - name: Enable FORCE_POST if requested
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force == 'true' }}
        run: echo "FORCE_POST=1" >> $GITHUB_ENV

      - name: Run YouTube runner
        env:
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS_YT }}
        run: python youtube_runner.py

      - name: Commit state if changed
        run: |
          rm -f client_secrets.json youtube_credentials.json
          if [[ -n "$(git status --porcelain state)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/*.json
            git commit -m "yt: update state"
            git push --force
          else
            echo "Aucun changement dans state/, rien à commit."
          fi
